[2025-09-05T09:48:22.884+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-05T09:48:22.890+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: molecular_dynamics_analysis.run_small_analysis manual__2025-09-05T09:48:21.963125+00:00 [queued]>
[2025-09-05T09:48:22.893+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: molecular_dynamics_analysis.run_small_analysis manual__2025-09-05T09:48:21.963125+00:00 [queued]>
[2025-09-05T09:48:22.894+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-09-05T09:48:22.899+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_small_analysis> on 2025-09-05 09:48:21.963125+00:00
[2025-09-05T09:48:22.901+0000] {standard_task_runner.py:72} INFO - Started process 659 to run task
[2025-09-05T09:48:22.903+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'molecular_dynamics_analysis', 'run_small_analysis', 'manual__2025-09-05T09:48:21.963125+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/molecular_dynamics_dag.py', '--cfg-path', '/tmp/tmp75h04rml']
[2025-09-05T09:48:22.905+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask run_small_analysis
[2025-09-05T09:48:22.911+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-05T09:48:22.925+0000] {task_command.py:467} INFO - Running <TaskInstance: molecular_dynamics_analysis.run_small_analysis manual__2025-09-05T09:48:21.963125+00:00 [running]> on host 54bcbc28a19e
[2025-09-05T09:48:22.955+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='molecular_dynamics_analysis' AIRFLOW_CTX_TASK_ID='run_small_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T09:48:21.963125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T09:48:21.963125+00:00'
[2025-09-05T09:48:22.955+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-05T09:48:22.962+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-05T09:48:22.963+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '/tmp/cpptraj/bin/cpptraj -p /opt/***/data/rerun_10us-traj/strip-wat-ions.caau-ol3-case-opc_NBfix-both-0BPhs_HMR_1.top -i /opt/***/scripts/nmr_unoe_ptraj.in']
[2025-09-05T09:48:22.967+0000] {subprocess.py:99} INFO - Output:
[2025-09-05T09:48:23.008+0000] {subprocess.py:106} INFO - Error: '/opt/***/data/rerun_10us-traj/strip-wat-ions.caau-ol3-case-opc_NBfix-both-0BPhs_HMR_1.top': No such file or directory
[2025-09-05T09:48:23.008+0000] {subprocess.py:106} INFO - Error: Could not open topology '/opt/***/data/rerun_10us-traj/strip-wat-ions.caau-ol3-case-opc_NBfix-both-0BPhs_HMR_1.top'
[2025-09-05T09:48:23.009+0000] {subprocess.py:106} INFO - Error: Error(s) occurred during execution.
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO - 
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO - CPPTRAJ: Trajectory Analysis. V6.29.14 (GitHub)
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO -     ___  ___  ___  ___
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO -      | \/ | \/ | \/ |
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO -     _|_/\_|_/\_|_/\_|_
[2025-09-05T09:48:23.011+0000] {subprocess.py:106} INFO - 
[2025-09-05T09:48:23.012+0000] {subprocess.py:106} INFO - | Date/time: 09/05/25 09:48:23
[2025-09-05T09:48:23.012+0000] {subprocess.py:106} INFO - | Available memory: 3.719 GB
[2025-09-05T09:48:23.012+0000] {subprocess.py:106} INFO - 
[2025-09-05T09:48:23.012+0000] {subprocess.py:106} INFO - TIME: Total execution time: 0.0050 seconds.
[2025-09-05T09:48:23.012+0000] {subprocess.py:106} INFO - 
[2025-09-05T09:48:23.012+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-05T09:48:23.018+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T09:48:23.022+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=molecular_dynamics_analysis, task_id=run_small_analysis, run_id=manual__2025-09-05T09:48:21.963125+00:00, execution_date=20250905T094821, start_date=20250905T094822, end_date=20250905T094823
[2025-09-05T09:48:23.028+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-05T09:48:23.029+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task run_small_analysis (Bash command failed. The command returned a non-zero exit code 1.; 659)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-05T09:48:23.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-05T09:48:23.053+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T09:48:23.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
